const messages = {
    'any.required': '{{#label}} là bắt buộc.',
    'any.unknown': '{{#label}} không được chấp nhận',
    'any.custom': '{{#label}} không hợp lệ',
    'any.default': '{{#label}} có giá trị mặc định',
    'any.failover': '{{#label}} có giá trị thay thế',
    'any.invalid': '{{#label}} không hợp lệ',
    'any.only': '{{#label}} phải là một trong những giá trị được chỉ định',
    'any.ref': '{{#label}} tham chiếu đến địa chỉ không hợp lệ',
    'date.base': '{{#label}} không hợp lệ.',
    'number.base': '{{#label}} phải là một số',
    'number.greater': '{{#label}} phải lớn hơn {{#limit}}',
    'number.infinity': '{{#label}} không thể là vô cực',
    'number.integer': '{{#label}} phải là số nguyên',
    'number.less': '{{#label}} phải nhỏ hơn {{#limit}}',
    'number.max': '{{#label}} phải nhỏ hơn hoặc bằng {{#limit}}',
    'number.min': '{{#label}} phải lớn hơn hoặc bằng {{#limit}}',
    'number.multiple': '{{#label}} phải là bội số của {{#multiple}}',
    'number.negative': '{{#label}} phải là số âm',
    'number.port': '{{#label}} phải là một cổng hợp lệ',
    'number.positive': '{{#label}} phải là số dương',
    'number.precision': '{{#label}} không được có nhiều hơn {{#limit}} chữ số thập phân',
    'number.unsafe': '{{#label}} phải là một số an toàn',
    'object.unknown': 'Trường {{#label}} không xác định',
    'string.alphanum': '{{#label}} chỉ được chứa ký tự chữ và số',
    'string.base': '{{#label}} phải là một chuỗi',
    'string.base64': '{{#label}} phải là một chuỗi base64 hợp lệ',
    'string.creditCard': '{{#label}} phải là một thẻ tín dụng hợp lệ',
    'string.dataUri': '{{#label}} phải là một chuỗi dataUri hợp lệ',
    'string.domain': '{{#label}} phải chứa một tên miền hợp lệ',
    'string.email': '{{#label}} không hợp lệ',
    'string.empty': '{{#label}} không được phép để trống',
    'string.guid': '{{#label}} phải là một GUID hợp lệ',
    'string.hex': '{{#label}} chỉ được chứa ký tự thập lục phân',
    'string.hexAlign': 'Biểu diễn hex giải mã của {{#label}} phải được căn chỉnh theo byte',
    'string.hostname': '{{#label}} phải là một tên máy chủ hợp lệ',
    'string.ip': '{{#label}} phải là một địa chỉ IP hợp lệ với CIDR {{#cidr}}',
    'string.ipVersion':
        '{{#label}} phải là một địa chỉ IP hợp lệ của một trong những phiên bản sau {{#version}} với CIDR {{#cidr}}',
    'string.isoDate': '{{#label}} phải ở định dạng iso',
    'string.isoDuration': '{{#label}} phải là một khoảng thời gian ISO 8601 hợp lệ',
    'string.length': 'Độ dài của {{#label}} phải là {{#limit}} ký tự',
    'string.lowercase': '{{#label}} chỉ được chứa ký tự thường',
    'string.max': 'Độ dài của {{#label}} phải nhỏ hơn hoặc bằng {{#limit}} ký tự',
    'string.min': 'Độ dài của {{#label}} phải ít nhất là {{#limit}} ký tự',
    'string.normalize': '{{#label}} phải được chuẩn hóa unicode ở dạng {{#form}}',
    'string.token': '{{#label}} chỉ được chứa ký tự chữ, số và gạch dưới',
    'string.pattern.base': '{{#label}} với giá trị {:[.]} không khớp với mẫu yêu cầu: {{#regex}}',
    'string.pattern.name': '{{#label}} với giá trị {:[.]} không khớp với mẫu {{#name}}',
    'string.pattern.invert.base': '{{#label}} với giá trị {:[.]} khớp với mẫu đảo ngược: {{#regex}}',
    'string.pattern.invert.name': '{{#label}} với giá trị {:[.]} khớp với mẫu đảo ngược {{#name}}',
    'string.trim': '{{#label}} không được chứa khoảng trắng đầu hoặc cuối chuỗi',
    'string.uri': '{{#label}} phải là một địa chỉ uri hợp lệ',
    'string.uriCustomScheme': '{{#label}} phải là một địa chỉ uri hợp lệ với một scheme khớp với mẫu {{#scheme}}',
    'string.uriRelativeOnly': '{{#label}} phải là một địa chỉ uri tương đối hợp lệ',
    'string.uppercase': '{{#label}} chỉ được chứa ký tự in hoa',
    'string.valid': '{{#label}} không hợp lệ.',
};

export default messages;
